import { Link, useParams } from 'react-router-dom';

import type { Claim, Citation, RiskHighlight } from '../api/types';
import { SeverityBadge } from '../components/Badges';
import { AlertIcon } from '../components/Icons';
import { useSummary } from '../hooks/useDocuments';

/**
 * A summary where every sentence is checkable.
 *
 * Each claim carries the store rows it was derived from, rendered as citation chips. That
 * is the whole design: the backend drops any claim whose citations do not resolve, so
 * what reaches this component is grounded by construction, and the chips let a reviewer
 * confirm it without taking the summary's word for anything.
 */
export function DocumentSummary() {
  const { documentId = null } = useParams();
  const { data, isPending, isError, error } = useSummary(documentId);

  if (isError) {
    return (
      <section className="panel panel-error">
        <h2>Could not load the summary</h2>
        <p>{(error as Error).message}</p>
      </section>
    );
  }
  if (isPending || !data) return <div className="skeleton" />;

  const { summary, cached, stale } = data;

  return (
    <>
      <header className="page-head">
        <h1>Summary</h1>
        <p className="muted">
          <code>{summary.document_id}</code> · generated by{' '}
          <span className="pill">{summary.provider}</span>
          {cached ? ' · cached' : ''}
        </p>
      </header>

      {stale ? (
        <section className="panel panel-error">
          <p>
            <AlertIcon size={15} /> This summary was written before the most recent change
            to the document&rsquo;s facts or findings.{' '}
            <Link to={`/documents/${summary.document_id}`}>Review the current data</Link>, or
            reload with <code>?refresh=true</code> to regenerate.
          </p>
        </section>
      ) : null}

      <section className="panel">
        <h2>Key terms</h2>
        <dl className="facts">
          <Term label="Parties" claims={summary.parties} />
          <Term label="Governing law" claims={summary.governing_law ? [summary.governing_law] : []} />
          <Term label="Liability cap" claims={summary.liability_cap ? [summary.liability_cap] : []} />
          <Term label="Payment" claims={summary.payment ? [summary.payment] : []} />
          <Term label="Term" claims={summary.term ? [summary.term] : []} />
          <Term label="Termination" claims={summary.termination ? [summary.termination] : []} />
        </dl>
      </section>

      {summary.key_obligations.length > 0 ? (
        <section className="panel">
          <h2>Obligations</h2>
          <ul className="cards">
            {summary.key_obligations.map((claim, index) => (
              <li className="card" key={index}>
                <ClaimText claim={claim} />
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {summary.top_risks.length > 0 ? (
        <section className="panel">
          <h2>Top risks</h2>
          <ul className="cards">
            {summary.top_risks.map((risk) => (
              <RiskCard key={risk.risk_id} risk={risk} />
            ))}
          </ul>
        </section>
      ) : null}

      {summary.unusual_clauses.length > 0 ? (
        <section className="panel">
          <h2>Worth a second look</h2>
          <ul className="cards">
            {summary.unusual_clauses.map((claim, index) => (
              <li className="card" key={index}>
                <ClaimText claim={claim} />
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {summary.coverage_notes.length > 0 ? (
        // Hatched, because `--hatch` already means "not real / struck through" here — and
        // this panel is precisely the list of things the summary could not see.
        <section className="panel card-suppressed">
          <h2>What this summary does not cover</h2>
          <ul>
            {summary.coverage_notes.map((note) => (
              <li key={note}>{note}</li>
            ))}
          </ul>
        </section>
      ) : null}
    </>
  );
}

function Term({ label, claims }: { label: string; claims: Claim[] }) {
  return (
    <>
      <dt>{label}</dt>
      <dd>
        {claims.length === 0 ? (
          // Absence is a finding in a contract, not a blank to be filled in.
          <span className="muted">Not stated in this document.</span>
        ) : (
          claims.map((claim, index) => <ClaimText claim={claim} key={index} />)
        )}
      </dd>
    </>
  );
}

function ClaimText({ claim }: { claim: Claim }) {
  return (
    <p>
      {claim.text}{' '}
      <span className="provenance">
        {claim.sources.map((source) => (
          <CitationChip key={`${source.kind}-${source.ref}`} citation={source} />
        ))}
      </span>
    </p>
  );
}

function CitationChip({ citation }: { citation: Citation }) {
  return (
    <span className="pill mono" title={`${citation.kind}: ${citation.ref}`}>
      {citation.kind === 'clause' ? citation.ref : `${citation.kind[0]}·${citation.ref}`}
    </span>
  );
}

function RiskCard({ risk }: { risk: RiskHighlight }) {
  return (
    <li className="card">
      <div className="card-head">
        <code>{risk.clause_ref}</code>
        <SeverityBadge severity={risk.severity} />
        <span className="mono">
          {risk.rule_id} v{risk.rule_version}
        </span>
      </div>
      <ClaimText claim={risk.statement} />
    </li>
  );
}
