"""Anti-drift on the redline fixtures.

Dev 1's dashboard builds against `fixtures/redline.sample.json` and
`fixtures/escalation.redline.json`. Both are generated by `python -m app.redline.pipeline
--publish`, so the risk is not that they are wrong — it is that someone changes the loop
and forgets to republish, and the frontend keeps building against a shape the backend no
longer emits.

The input fixtures are checked too. `risk.sample.json` and `playbook.sample.json` are
hand-written proposals to Dev 4 in the `schema.sql` shape; if they stop validating
against the models, the two sides have diverged and this is where it should surface.
"""

import pytest

from app.redline.generator import run
from app.redline.provider import MockRedlineProvider
from app.schemas import EscalationRecord, PlaybookRule, Redline, ReviewStatus, RiskFlag
from tests.conftest import load


@pytest.fixture
def result(sample_risks, sample_playbook, retrieval_context):
    return run(sample_risks, sample_playbook, retrieval_context, MockRedlineProvider())


@pytest.mark.parametrize(
    "name, model",
    [
        ("risk.sample.json", RiskFlag),
        ("playbook.sample.json", PlaybookRule),
        ("redline.sample.json", Redline),
    ],
)
def test_published_fixtures_validate(name, model):
    items = load(name)
    assert items, f"{name} is empty; downstream devs have nothing to build against"
    for item in items:
        model.model_validate(item)


def test_published_escalation_fixture_validates():
    items = load("escalation.redline.json")
    assert items
    for item in items:
        EscalationRecord.model_validate(item)


def test_redline_fixture_matches_a_fresh_run(result):
    assert load("redline.sample.json") == [r.model_dump(mode="json") for r in result.redlines]


def test_escalation_fixture_matches_a_fresh_run(result):
    assert load("escalation.redline.json") == [
        {"id": escalation_id, "target_redline_id": redline_id, **record.model_dump(mode="json")}
        for escalation_id, redline_id, record in result.escalations
    ]


def test_every_flag_names_a_rule_that_exists(sample_risks, sample_playbook):
    """The join Dev 4's schema makes on `(rule_id, rule_version)`.

    Versioned on purpose: a redline has to be justified against the rule that actually
    fired, not against whatever the active version happens to be when someone reads it.
    """
    versions = {(r.rule_id, r.version) for r in sample_playbook}
    for risk in sample_risks:
        assert (risk.rule_id, risk.rule_version) in versions, risk.id


def test_the_fixtures_still_exercise_every_exit(result):
    """If someone edits the input fixtures, the loop's coverage must not quietly shrink."""
    assert {r.status for r in result.redlines} == {
        ReviewStatus.CONFIRMED,
        ReviewStatus.PENDING_REVIEW,
    }
    assert len(result.escalations) == 2
    assert result.suppressed
