"""Building, caching and serving a contract summary."""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.orm import Session

from app import models
from app.compare.assemble import assemble_clauses
from app.kg import store as kg_store
from app.redline import store as redline_store
from app.risk import store as risk_store
from app.schemas import PlaybookRule, ReviewStatus
from app.summary.provider import SummaryRequest, get_provider
from app.summary.schemas import ContractSummary, SummaryResponse
from app.summary.validate import citable_ids, coverage_notes, enforce_citations


def _fingerprint(*, clauses, facts, risks, edges, redlines) -> str:
    """Hash the identity of every input row.

    Ids only, not content: a fact's id is stable while its value is not, and the point is
    to detect "the inputs changed" cheaply. Content changes to an existing row do move the
    fingerprint too, because ids are regenerated by the extractor on each run.
    """
    parts = (
        sorted(clauses)
        + sorted(f.fact_id for f in facts)
        + sorted(r.id for r in risks)
        + sorted(e.edge_id for e in edges)
        + sorted(r.redline_id for r in redlines)
    )
    return hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()


def build_request(session: Session, document: models.Document) -> tuple[SummaryRequest, list[str], str]:
    """Gather the stored rows a summary is built from."""
    document_id = document.document_id
    chunks = kg_store.list_chunks(session, document_id)
    clauses = assemble_clauses(chunks)
    facts = kg_store.list_facts(session, document_id)
    risks = risk_store.list_risk_flags(session, document_id)
    edges = kg_store.list_edges(session, document_id)  # confirmed only
    pending = kg_store.list_edges(session, document_id, status=ReviewStatus.PENDING_REVIEW)
    redlines = redline_store.list_redlines(session, document_id)

    rule_rows = session.scalars(
        select(models.PlaybookRule).where(
            models.PlaybookRule.rule_id.in_({r.rule_id for r in risks} or {""})
        )
    )
    rules = {
        (row.rule_id, row.version): PlaybookRule.model_validate(
            {
                "rule_id": row.rule_id,
                "version": row.version,
                "is_active": row.is_active,
                "clause_pattern": row.clause_pattern,
                "conditions": row.conditions,
                "severity": row.severity,
                "rationale": row.rationale,
                "allowed_overrides": row.allowed_overrides or [],
                "standard_language": row.standard_language,
            }
        )
        for row in rule_rows
    }

    request = SummaryRequest(
        document_id=document_id,
        filename=document.title or document.filename,
        clauses=clauses,
        facts=facts,
        risks=risks,
        rules=rules,
        edges=edges,
        redlines=redlines,
        citable=citable_ids(
            clauses=clauses, facts=facts, risks=risks, edges=edges, redlines=redlines
        ),
    )
    notes = coverage_notes(
        clauses=clauses,
        edges_pending=len(pending),
        worst_ocr=min((c.min_ocr_confidence for c in clauses.values()), default=1.0),
    )
    return request, notes, _fingerprint(
        clauses=clauses, facts=facts, risks=risks, edges=edges, redlines=redlines
    )


def generate(session: Session, document: models.Document) -> ContractSummary:
    request, notes, fingerprint = build_request(session, document)
    provider = get_provider()
    raw = provider.summarize(request)

    summary = ContractSummary.model_validate(
        {
            **raw,
            "document_id": document.document_id,
            "generated_at": datetime.now(UTC),
            "provider": getattr(provider, "name", "mock"),
            "input_fingerprint": fingerprint,
            "coverage_notes": notes,
        }
    )
    # After the model, before the store. A fabricated citation never reaches the database.
    return enforce_citations(summary, request.citable)


def save(session: Session, summary: ContractSummary) -> None:
    session.merge(
        models.Summary(
            document_id=summary.document_id,
            input_fingerprint=summary.input_fingerprint,
            provider=summary.provider,
            payload=summary.model_dump(mode="json"),
        )
    )
    session.commit()


def get_or_generate(
    session: Session, document: models.Document, *, refresh: bool = False
) -> SummaryResponse:
    row = session.get(models.Summary, document.document_id)
    if row is not None and not refresh:
        _, _, fingerprint = build_request(session, document)
        stale = row.input_fingerprint != fingerprint
        return SummaryResponse(
            summary=ContractSummary.model_validate(row.payload), cached=True, stale=stale
        )

    summary = generate(session, document)
    save(session, summary)
    return SummaryResponse(summary=summary, cached=False, stale=False)
